Single responsibility principle
Open/closed principle
Liskov substitution principle
Interface segregation principle
Dependency inversion

Liskov substitution principle  - betyder at en klasse der bruger en anden klasse skal kunne bruge alle underklasser af 
"den anden klasse" - dvs i en polymorf sammenhæng - således at man ikke skal tage højde for forskelle i hhv superklassen 
og dens underklasser, fordi de alle på overfladen opfører sig ens. I praksis er dette en udvidelse af open/closed princippet. 
Princippet medfører, at man ikke må lavere en strengere eller mere restriktiv behandling af input parametere i en underklasse      
