Single responsibility principle
Open/closed principle
Liskov substitution principle
Interface segregation principle
Dependency inversion

Liskov substitution principle  - betyder at en klasse der bruger en anden klasse skal kunne bruge alle underklasser af 
"den anden klasse" - dvs i en polymorf sammenhæng - således at man ikke skal tage højde for forskelle i hhv superklassen 
og dens underklasser, fordi de alle på overfladen opfører sig ens.   
